summary: Create new github actions agent

environment:
    AGENT_NAME: $AGENT_PREFIX-$AGENT_ID

prepare: |
    test -n "$AGENT_ID"
    test -n "$AGENT_PREFIX"
    test -n "$AGENT_USER"
    test -n "$GITHUB_TOKEN"
    test -f "$DATA_PATH"/spread-runner.tar

restore: |
    # Clean up the environment
    lxd.lxc exec "$AGENT_NAME" -- apt-get clean
    lxd.lxc exec "$AGENT_NAME" -- rm -rf /tmp/spread-runner{,.tar}
    lxd.lxc exec "$AGENT_NAME" -- rm -f /etc/sudoers.d/90-cloud-init-users

execute: |
    lxd.lxc delete --force "$AGENT_NAME" || true
    lxd.lxc launch ubuntu:18.04 "$AGENT_NAME"

    echo "Setting up proxy for lxc"
    if [ -n "${HTTPS_PROXY:-}" ]; then
        lxd.lxc config set core.proxy_https "$HTTPS_PROXY"
    fi

    lxd.lxc exec "$AGENT_NAME" -- ls -ld /tmp
    lxd.lxc config set "$AGENT_NAME" boot.autostart true
    lxd.lxc config set "$AGENT_NAME" boot.autostart.delay 16
    lxd.lxc file push "$DATA_PATH"/spread-runner.tar "$AGENT_NAME"/tmp/spread-runner.tar
    lxd.lxc exec "$AGENT_NAME" -- tar -C /tmp -xf /tmp/spread-runner.tar
    lxd.lxc --cwd /tmp/spread-runner exec "$AGENT_NAME" -- ./setup-agent.sh
    lxd.lxc --cwd /tmp/spread-runner exec "$AGENT_NAME" -- ./setup-sa.sh
  
    # Install & start the actions runner 
    USER_ID="$(lxd.lxc exec "$AGENT_NAME" -- id -u $AGENT_USER)"
    if [ -n "${HTTPS_PROXY:-}" ]; then
        echo "https_proxy=$HTTPS_PROXY" | lxd.lxc --user "$USER_ID" --cwd "/home/$AGENT_USER/actions-runner" exec "$AGENT_NAME" -- tee -a .env
        echo "HTTPS_PROXY=$HTTPS_PROXY" | lxd.lxc --user "$USER_ID" --cwd "/home/$AGENT_USER/actions-runner" exec "$AGENT_NAME" -- tee -a .env
        echo "http_proxy=$HTTPS_PROXY" | lxd.lxc --user "$USER_ID" --cwd "/home/$AGENT_USER/actions-runner" exec "$AGENT_NAME" -- tee -a .env
        echo "HTTP_PROXY=$HTTPS_PROXY" | lxd.lxc --user "$USER_ID" --cwd "/home/$AGENT_USER/actions-runner" exec "$AGENT_NAME" -- tee -a .env
    fi
    lxd.lxc --user "$USER_ID" --cwd "/home/$AGENT_USER/actions-runner" exec "$AGENT_NAME" -- ./config.sh --unattended --url https://github.com/snapcore/snapd --token $GITHUB_TOKEN
    lxd.lxc --user "$USER_ID" --cwd "/home/$AGENT_USER/actions-runner" exec "$AGENT_NAME" -- sudo ./svc.sh install
    lxd.lxc --user "$USER_ID" --cwd "/home/$AGENT_USER/actions-runner" exec "$AGENT_NAME" -- sudo ./svc.sh start
    lxd.lxc exec "$AGENT_NAME" -- systemctl disable --now ssh.service unattended-upgrades.service networkd-dispatcher.service atd.service cron.service
