summary: Update containers with the code needed

prepare: |
    test -n "$AGENT_PREFIX"

execute: |
    if [ -z "$AGENT_ID" ]; then
        agents=$(lxd.lxc list --format csv | cut -d ',' -f1)
        
        for agent_name in $agents; do
            echo "Updating the agent"
            # ADD THE CODE HERE
        done
    else
        agent_name="$AGENT_PREFIX-$AGENT_ID"
        # ADD THE CODE HERE
    fi
