summary: Delete a github actions agent

environment:
    AGENT_NAME: $AGENT_PREFIX-$AGENT_ID

prepare: |
    test -n "$AGENT_ID"
    test -n "$AGENT_USER"
    test -n "$GITHUB_TOKEN"
    test -n "$(command -v lxd.lxc)"

execute: |
    if lxd.lxc info "$AGENT_NAME" | MATCH "Status: Running"; then
        lxd.lxc --cwd "/home/$AGENT_USER/actions-runner" exec "$AGENT_NAME" -- ./svc.sh stop || true
        lxd.lxc --cwd "/home/$AGENT_USER/actions-runner" exec "$AGENT_NAME" -- ./svc.sh uninstall || true
        lxd.lxc --cwd "/home/$AGENT_USER/actions-runner" exec "$AGENT_NAME" -- ./config.sh remove --token "$GITHUB_TOKEN" || true
    fi
    lxd.lxc delete --force "$AGENT_NAME" || true
